cloudfoundry/garden-runc-release

jobs/garden/spec, jobs/garden/templates/garden_ctl.erb
This implements a `garden.dns_servers` property which will force the container to use those DNS servers rather than guessing from the host's `resolv.conf`.
See also cloudfoundry-incubator/garden-linux#60.
This depends on ~~cloudfoundry-incubator/garden#45~~ and cloudfoundry-incubator/guardian#17.
Edit: This doesn't _actually_ depend on changing `garden`. Closed that one.
=> Support using custom DNS servers instead of picking from the host

jobs/garden/monit, jobs/garden/spec, jobs/garden/templates/share_mount.erb, jobs/garden/templates/share_mounts.erb
The recent changes to guardian to unshare the mount namespace have caused [failures in the ducati acceptance tests][1]. One way to resolve the issue is to explicitly create a bind mount for our data location and share that mount point so it propagates into the guardian namespace.
We have made the list of directories configurable so we can preserve the current paths.
/cc @rosenhouse
[1]: https://www.pivotaltracker.com/story/show/116097425
=> Shared mount

jobs/garden/templates/garden_ctl.erb
- Fixes the following issue `runc create: exit status 1: could not
create session key: disk quota exceeded` that occurs when a lot of
containers are created simultaneously
Related Slack context/discussion: https://cloudfoundry.slack.com/archives/garden/p1468012069004093
Screenshot of keyring limit issue that this PR fixes:
We've been running our Buildpacks team Concourse deployment with this fix applied for ~3 weeks now and it's been stable/we haven't seen the issue reappear.
=> Increase max keyrings from 500 to 1000000

jobs/garden/templates/garden_ctl.erb
Several of the CF and Diego platform services send logs to the local syslog, tagged as `vcap.*`. . The [metron agent from loggregrator configures the local syslog to send the logs to metron](https://github.com/cloudfoundry/loggregator/blob/develop/jobs/metron_agent/spec#L29) so that later can be sent to a centralised logging service. 
In some cases it is the service application itself who sends the logs to syslog, but it seems to be a common pattern across CF and Diego services to [let the service log to stdout/stderr, and redirect that output to local files or syslog](https://github.com/cloudfoundry/diego-release/blob/develop/jobs/bbs/templates/bbs_as_vcap.erb#L91) using the [`logger` command](http://linux.die.net/man/1/logger). 
Not all the services implement this feature, and instead …
=> Implement logic to send service logs to syslog

jobs/garden/templates/garden_ctl.erb
I'm attempting to use garden-runc in an environment that does not have app armor enabled.  This change allows deployments to explicitly set garden.apparmor_profile to an empty string so garden-runc does not attempt activate the app armor policy paths. By default, the app armor policy is still used.
> Note: Regardless of these changes, the job spec allows users to change the policy name but the start script hard-coded `garden-default`. It's also strange that the policy is a release template but there's no way to customize it. A nice feature would be to provide a mechanism for deployments to include a custom policy definition.
=> Provide mechanism to opt-out of app armor

jobs/garden/spec
Reasoning included in commit message.
Note: with this change, Diego can probably stop configuring this in their manifest. This change is also needed for Concourse's new container/volume lifecycle where we no longer heartbeat with GraceTime and instead have an explicit GC.
Alternatively we could remove this property? That would mean `0` means indefinite. Or we could keep it and make the `GraceTime` field a pointer, where `nil` would mean "server default" and `0` would mean "indefinite". (Or some other approach to add the distinction.)
=> default grace time to indefinite

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
This allows us to use a custom image plugin which works on windows.
@sesmith177 @mdelillo
=> Add configuration for an image plugin in garden-windows

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
- to support stream in/out
- the provided path is the default path for tar on the Windows stemcell
[#146150119]
=> add --tar-bin flag to garden-windows gdn args

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
This allows a diego cell with garden-windows to be redeployed by BOSH
[#148146569]
Signed-off-by: Sam Smith <sesmith177@gmail.com>
=> Add destroy_containers_on_start property to garden-windows

jobs/garden-windows/templates/garden_ctl.ps1.erb
Image and Runtime plugins should use the same sandbox directory. This is a limitation of HCS when creating containers on Windows.
[#149185707]
Signed-off-by: Amin Jamali <ajamali@pivotal.io>
=> Use image store when starting Guardian on Windows

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
also adds:
- powershell exception handling
- cleaner directory/path creation
- log level configuration
- `--runc-root` flag was incorrectly nested inside of `destroy-containers-on-startup` if block
=> add default container rootfs for windows job

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
used for specifying a config file to the network plugin
=> add extra network plugin args property to garden-windows

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb
Also, ensure --image-store is passed to runtime plugin as an extra arg
This enables adding extra args for image plugin logging, see: https://www.pivotaltracker.com/story/show/152332149
=> Add image_plugin_extra_args property to garden-windows

jobs/garden/spec, jobs/garden/templates/bin/garden_start.erb
Quotes are necessary in the `garden_start.erb` so one can add things like `127.0.0.1	homesweethome`
=> add BOSH property to use --additional-host-entry

jobs/garden-windows/templates/garden_ctl.ps1.erb
Since we are moving to use our groot-based image plugin, the directories
and command line flags specified here are no longer correct or needed
=> Remove image store from garden-windows job

jobs/garden/spec, jobs/garden/templates/config/config.ini.erb
Signed-off-by: Michael Maximilien <maxim@us.ibm.com>
does not contain submodule bump
=> add an option to disable swap limits

jobs/garden-windows/spec, jobs/garden-windows/templates/garden_ctl.ps1.erb, jobs/garden/spec
Analogue of https://github.com/cloudfoundry/garden-runc-release/pull/78 for the garden-windows job.
Also removes experimental language from corresponding property on the garden job.
=> Add log-format configurability to garden-windows

jobs/garden/templates/bin/garden_start.erb
For the `garden` job, during start time.
Use `mkdir -p` to create the `/var/vcap/sys/log/garden` dir, in case is not there.
It should do nothing, if the dir already exists.
=> Ensure the /var/vcap/sys/log/garden dir exists

jobs/garden/spec, jobs/garden/templates/config/config.ini.erb
Tested manually in both the positive and the negative against a Concourse deployment.
I tried indenting the conditionals, but then the actual config ended up indented. I had a look for ERB style guides, but didn't find a conclusive answer regarding indentation of nested `if`s. Then I had a flashback of writing PHP and JSP and having to care about such things, broke out in a cold sweat, and then decided it probably doesn't matter too much*.
*_Some of the stories in this comment may not be factually accurate._
=> allow no-image-plugin to be provided via manifest properties

docs/cpu-entitlement.md
According to my understand, 256MB application with 256 cpu shares and a value of 0.3 for `experimental_cpu_entitlement_per_share_in_percent` would have access to **76.8%** of the total CPU instead of **78.6%**. It seems that it's a slip of the pen.
Hope it helpful.
=> correct the calculation error of cpu entitlement doc on cpu allocation

src/thresholder/go.mod, src/thresholder/go.sum, src/thresholder/vendor/modules.txt
I'll need to make smaller PRs for the golang.org/x/text fixes since there's a ton of submoduling.
=> Thresholder: force safe golang.org/x/text

packages/xfs-progs/packaging
The newer GCC compiler (10+) has tightened its requirements, throwing errors that were previously ignored. newer stemcells, e.g. the upcoming Ubuntu 22.04 Jammy Jellyfish, include the newer GCC.
This change will allow the Garden-runC release to build on newer stemcells.
From _[Porting to GCC 10](https://gcc.gnu.org/gcc-10/porting_to.html)_
> Default to -fno-common ... In previous GCC versions this error is ignored. GCC 10 defaults to -fno-common, which means a linker error will now be reported
fixes:
```
Task 46850 | 21:35:18 | Compiling packages: xfs-progs/b8baad87ddfdd32b428001fbdf4b2fd4e1bb9a28a4aa196782d3e5f92650d546 (00:07:20)
L Error: Action Failed get_task: Task eeebef25-e9be-4d4a-47c2-06905757de07 result: Compiling package xfs-progs: Running packaging script: Running packaging …
```
=> Accommodate GCC 10 Changes

config/blobs.yml, packages/tar/packaging, packages/tar/spec
Glibc is still loading some libraries dynamically even though we compile
tar statically. If runtime glibc version (in container rootfs) is
different from the compilation glibc version there are might be
incompatible errors. We observed the following error when using Ubuntu
jammy and cflinuxfs3 during droplet stream-out:
https://sourceware.org/bugzilla/show_bug.cgi?id=27790
The issue is that we use tar on a host compiled in garden-runc-release
with glibc in ubuntu jammy. Then, we use nstar to stream in/out data
from the container. Nstar is switching namespace to container rootfs and
thus using glibc in linuxfs3.
Instead of using glibc we build tar with musl-gcc.
"Some of musl's major advantages over glibc and uClibc/uClibc-ng are its
size, correctness, static linking support, and clean …
=> Compile tar with musl-gcc

jobs/garden/spec
Due to compatibility issues between the bundled version of iptables in
`garden-runc-release` and system-bundled iptables on Xenial and Jammy,
we are migrating away from preferring the bundled version of iptables.
It was provided to ensure compatibility with OSes that bundled versions
of iptables prior to 1.6.x, as garden + silk rely on networking features
from it. However, we do not support any stemcells that old anymore.
If needed, this is still available for overriding, but changing the
default is the easiest way to ensure compatibility between garden/silk
iptables and system iptables functionality.
=> Revert to system iptables for better compatibility

jobs/garden-binaries/spec, manifests/include-garden-binaries.ops.yml
This avoids issues (https://github.com/cloudfoundry/garden-runc-release/issues/233) using `gdn` compiled binaries in BOSH deployments on `jammy` in a way that allows for use in other stemcell lines as well.
By providing the `guardian-binaries` job, other releases can consume `gdn`/`iptables`/`tar`/etc. binaries built on the same stemcell. This will unblock [BOSH deployed Concourse](https://github.com/concourse/concourse-bosh-release) support for Jammy stemcells.
This does not address issues with consuming the `gdn` binary from tagged GitHub releases, which is an issue currently blocking Concourse in containers from supporting `jammy` and `bionic` fully.
@anEXPer @xtremerui
=> create a job providing garden binaries

jobs/garden/spec, jobs/garden/templates/config/config.ini.erb, spec/jobs/garden_spec.rb
* adding non-experimental properties for the two cpu throttling properties.
* if the non-experimental properties are present, they take precedent over the experimental ones.
* we should clean up the experimental properties later, but I think allowing some overlap will make migration easier.
` ./scripts/template-tests`
=> GA CPU throttling
